#!/usr/bin/env bash
# bootloader.sh — GRUB installation, os-prober, dual-boot
source "${LIB_DIR}/protection.sh"

# bootloader_install — Install and configure GRUB
bootloader_install() {
    einfo "Installing bootloader (GRUB)..."

    # Install GRUB to ESP
    local grub_target="/boot/efi"
    local grub_id="LFS"

    chroot_exec "
        grub-install --target=x86_64-efi \
                     --efi-directory=${grub_target} \
                     --bootloader-id=${grub_id} \
                     --recheck
    "

    # Configure GRUB
    _configure_grub

    # Generate GRUB config
    chroot_exec "grub-mkconfig -o /boot/grub/grub.cfg"

    einfo "Bootloader installation complete"
}

# _configure_grub — Set up /etc/default/grub
_configure_grub() {
    einfo "Configuring GRUB..."

    local root_uuid
    root_uuid=$(get_uuid "${ROOT_PARTITION}")

    local extra_params=""
    if [[ "${FILESYSTEM:-ext4}" == "btrfs" ]]; then
        extra_params="rootflags=subvol=@"
    fi

    chroot_exec "
        mkdir -p /etc/default
        cat > /etc/default/grub << 'GRUBEOF'
# /etc/default/grub
# Generated by ${INSTALLER_NAME} v${INSTALLER_VERSION}

GRUB_DEFAULT=0
GRUB_TIMEOUT=5
GRUB_TIMEOUT_STYLE=menu
GRUB_DISTRIBUTOR=\"Linux From Scratch\"

GRUB_CMDLINE_LINUX_DEFAULT=\"quiet\"
GRUB_CMDLINE_LINUX=\"${extra_params}\"

GRUB_TERMINAL_INPUT=\"console\"
GRUB_TERMINAL_OUTPUT=\"gfxterm\"
GRUB_GFXMODE=\"auto\"
GRUB_GFXPAYLOAD_LINUX=\"keep\"
GRUBEOF
    "

    # Dual-boot: enable os-prober
    if [[ "${WINDOWS_DETECTED:-0}" == "1" ]] || [[ "${ESP_REUSE:-no}" == "yes" ]]; then
        # Build and install os-prober if source available
        chroot_exec "
            if [[ -f /sources/os-prober-*.tar.* ]]; then
                cd /sources && tar xf os-prober-*.tar.* && cd os-prober-*/ && \
                make && install -vm755 os-prober /usr/bin/ && \
                install -vm755 linux-boot-prober /usr/bin/ && \
                cd /sources && rm -rf os-prober-*/
            fi
        " || true

        chroot_exec "
            echo '' >> /etc/default/grub
            echo '# Dual-boot: os-prober enabled' >> /etc/default/grub
            echo 'GRUB_DISABLE_OS_PROBER=false' >> /etc/default/grub
        "
        einfo "os-prober enabled for dual-boot detection"
    fi

    einfo "GRUB configured"
}
