#!/usr/bin/env bash
# network.sh — Network checks, LFS network configuration
source "${LIB_DIR}/protection.sh"

check_network() {
    einfo "Checking network connectivity..."

    if has_network; then
        einfo "Network connectivity OK"
        return 0
    else
        eerror "No network connectivity"
        return 1
    fi
}

# configure_network — Set up SysVinit network configuration
configure_network() {
    local hostname="${HOSTNAME:-lfs}"
    local iface="${NETWORK_IFACE:-eth0}"

    einfo "Configuring network for ${iface}..."

    # Detect primary interface if not set
    if [[ "${iface}" == "eth0" ]]; then
        local detected
        detected=$(ip -o link show 2>/dev/null | awk -F': ' '!/lo/{print $2; exit}') || true
        if [[ -n "${detected}" ]]; then
            iface="${detected}"
        fi
    fi

    # Create ifconfig script for the interface
    mkdir -p /etc/sysconfig
    if [[ -n "${NETWORK_IP:-}" ]]; then
        # Static IP
        cat > "/etc/sysconfig/ifconfig.${iface}" << NETEOF
ONBOOT=yes
IFACE=${iface}
SERVICE=ipv4-static
IP=${NETWORK_IP}
GATEWAY=${NETWORK_GATEWAY:-}
PREFIX=24
BROADCAST=
NETEOF
    else
        # DHCP (requires dhcpcd to be built)
        cat > "/etc/sysconfig/ifconfig.${iface}" << NETEOF
ONBOOT=yes
IFACE=${iface}
SERVICE=dhclient
DHCP_START=""
DHCP_STOP=""
NETEOF
    fi

    # DNS configuration
    if [[ -n "${NETWORK_DNS:-}" ]]; then
        {
            echo "# /etc/resolv.conf"
            echo "# Generated by LFS TUI Installer"
            local dns
            for dns in ${NETWORK_DNS}; do
                echo "nameserver ${dns}"
            done
        } > /etc/resolv.conf
    fi

    # /etc/hostname
    echo "${hostname}" > /etc/hostname

    # /etc/hosts
    cat > /etc/hosts << HOSTSEOF
# /etc/hosts
127.0.0.1   localhost
::1         localhost
127.0.1.1   ${hostname}.localdomain ${hostname}
HOSTSEOF

    einfo "Network configuration complete"
}
