#!/usr/bin/env bash
# system.sh — Chapter 9: LFS system configuration
# SysVinit bootscripts, network, locale, timezone, hostname, fstab, users
source "${LIB_DIR}/protection.sh"

# --- LFS Bootscripts ---

install_lfs_bootscripts() {
    einfo "Installing LFS bootscripts..."

    chroot_exec "
        cd /sources && tar xf lfs-bootscripts-*.tar.xz && cd lfs-bootscripts-*/ && \
        make install && \
        cd /sources && rm -rf lfs-bootscripts-*/
    "

    einfo "LFS bootscripts installed"
}

# --- Timezone ---

system_set_timezone() {
    local tz="${TIMEZONE:-UTC}"
    einfo "Setting timezone: ${tz}"

    chroot_exec "
        ln -sfv /usr/share/zoneinfo/${tz} /etc/localtime
    "

    # Create /etc/sysconfig/clock for SysVinit
    chroot_exec "
        mkdir -p /etc/sysconfig
        cat > /etc/sysconfig/clock << 'CLKEOF'
UTC=1
CLOCKPARAMS=
CLKEOF
    "
}

# --- Locale ---

system_set_locale() {
    local locale="${LOCALE:-en_US.UTF-8}"
    einfo "Setting locale: ${locale}"

    local lang="${locale%%.*}"
    local charset="${locale#*.}"

    # Generate locale
    chroot_exec "
        mkdir -p /usr/lib/locale
        localedef -i ${lang} -f ${charset} ${locale} 2>/dev/null || true
        localedef -i C -f UTF-8 C.UTF-8 2>/dev/null || true
    "

    # Create /etc/profile.d/locale.sh
    chroot_exec "
        mkdir -p /etc/profile.d
        cat > /etc/profile.d/locale.sh << 'LOCEOF'
export LANG=${locale}
export LC_ALL=${locale}
LOCEOF
    "

    # Set /etc/locale.conf
    chroot_exec "
        cat > /etc/locale.conf << 'LCONF'
LANG=${locale}
LCONF
    "
}

# --- Hostname ---

system_set_hostname() {
    local hostname="${HOSTNAME:-lfs}"
    einfo "Setting hostname: ${hostname}"

    chroot_exec "echo '${hostname}' > /etc/hostname"

    chroot_exec "
        cat > /etc/hosts << 'HOSTSEOF'
127.0.0.1   localhost
::1         localhost
127.0.1.1   ${hostname}.localdomain ${hostname}
HOSTSEOF
    "
}

# --- Keymap ---

system_set_keymap() {
    local keymap="${KEYMAP:-us}"
    einfo "Setting keymap: ${keymap}"

    # Console configuration for SysVinit
    chroot_exec "
        mkdir -p /etc/sysconfig
        cat > /etc/sysconfig/console << CONEOF
KEYMAP=\"${keymap}\"
FONT=\"lat1-16\"
CONEOF
    "
}

# --- fstab ---

generate_fstab() {
    einfo "Generating /etc/fstab..."

    local fs="${FILESYSTEM:-ext4}"

    local root_uuid
    root_uuid=$(get_uuid "${ROOT_PARTITION}")
    local esp_uuid
    esp_uuid=$(get_uuid "${ESP_PARTITION}")

    local fstab_content=""
    fstab_content+="# /etc/fstab\n"
    fstab_content+="# Generated by ${INSTALLER_NAME} v${INSTALLER_VERSION}\n"
    fstab_content+="#\n"
    fstab_content+="# <fs>                                  <mountpoint>  <type>  <opts>                                  <dump/pass>\n"

    # Root filesystem
    if [[ -n "${root_uuid}" ]]; then
        case "${fs}" in
            btrfs)
                fstab_content+="UUID=${root_uuid}   /             btrfs   subvol=@,compress=zstd,noatime,defaults  0 1\n"
                if [[ -n "${BTRFS_SUBVOLUMES:-}" ]]; then
                    local IFS=':'
                    local -a parts
                    read -ra parts <<< "${BTRFS_SUBVOLUMES}"
                    local idx
                    for (( idx = 0; idx < ${#parts[@]}; idx += 2 )); do
                        local subvol="${parts[$idx]}"
                        local mpoint="${parts[$((idx + 1))]}"
                        [[ "${subvol}" == "@" ]] && continue
                        fstab_content+="UUID=${root_uuid}   ${mpoint}          btrfs   subvol=${subvol},compress=zstd,noatime,defaults  0 2\n"
                    done
                fi
                ;;
            ext4)
                fstab_content+="UUID=${root_uuid}   /             ext4    noatime,defaults        0 1\n"
                ;;
            xfs)
                fstab_content+="UUID=${root_uuid}   /             xfs     noatime,defaults        0 1\n"
                ;;
        esac
    else
        fstab_content+="${ROOT_PARTITION}              /             ${fs}     noatime,defaults        0 1\n"
    fi

    # ESP
    if [[ -n "${esp_uuid}" ]]; then
        fstab_content+="UUID=${esp_uuid}   /boot/efi     vfat    noatime,defaults        0 2\n"
    else
        fstab_content+="${ESP_PARTITION}              /boot/efi     vfat    noatime,defaults        0 2\n"
    fi

    # Swap partition
    if [[ "${SWAP_TYPE:-}" == "partition" && -n "${SWAP_PARTITION:-}" ]]; then
        local swap_uuid
        swap_uuid=$(get_uuid "${SWAP_PARTITION}")
        if [[ -n "${swap_uuid}" ]]; then
            fstab_content+="UUID=${swap_uuid}   none          swap    sw              0 0\n"
        else
            fstab_content+="${SWAP_PARTITION}              none          swap    sw              0 0\n"
        fi
    fi

    # Standard entries
    fstab_content+="proc                                    /proc         proc    nosuid,noexec,nodev     0 0\n"
    fstab_content+="sysfs                                   /sys          sysfs   nosuid,noexec,nodev     0 0\n"
    fstab_content+="devpts                                  /dev/pts      devpts  gid=5,mode=620          0 0\n"
    fstab_content+="tmpfs                                   /run          tmpfs   defaults                0 0\n"
    fstab_content+="devtmpfs                                /dev          devtmpfs mode=0755,nosuid       0 0\n"
    fstab_content+="tmpfs                                   /dev/shm      tmpfs   nosuid,nodev            0 0\n"

    echo -e "${fstab_content}" > "${LFS}/etc/fstab"

    einfo "fstab generated"
}

# --- Users ---

system_create_users() {
    einfo "Creating users..."

    # Set root password
    if [[ -n "${ROOT_PASSWORD_HASH:-}" ]]; then
        chroot_exec "
            usermod -p '${ROOT_PASSWORD_HASH}' root
        "
        einfo "Root password set"
    fi

    # Create regular user
    if [[ -n "${USERNAME:-}" ]]; then
        local groups="${USER_GROUPS:-wheel,audio,video,input}"

        chroot_exec "
            useradd -m -G ${groups} -s /bin/bash ${USERNAME} 2>/dev/null || true
        "

        if [[ -n "${USER_PASSWORD_HASH:-}" ]]; then
            chroot_exec "
                usermod -p '${USER_PASSWORD_HASH}' ${USERNAME}
            "
        fi

        # Configure sudo
        chroot_exec "
            mkdir -p /etc/sudoers.d
            echo '%wheel ALL=(ALL:ALL) ALL' > /etc/sudoers.d/wheel
            chmod 0440 /etc/sudoers.d/wheel
        "

        einfo "User ${USERNAME} created with groups: ${groups}"
    fi

    # SSH
    if [[ "${ENABLE_SSH:-no}" == "yes" ]]; then
        chroot_exec "
            if [[ -f /etc/init.d/sshd ]]; then
                ln -sf ../init.d/sshd /etc/rc.d/rc3.d/S30sshd 2>/dev/null || true
            fi
        "
        einfo "SSH server enabled"
    fi
}

# --- Filesystem tools ---

install_filesystem_tools() {
    local fs="${FILESYSTEM:-ext4}"
    einfo "Filesystem tools for ${fs} included in base system"

    # e2fsprogs is already built in Chapter 8
    # Install additional tools for btrfs/xfs if needed
    case "${fs}" in
        btrfs)
            einfo "Note: btrfs-progs will need to be built from BLFS"
            ;;
        xfs)
            einfo "Note: xfsprogs will need to be built from BLFS"
            ;;
    esac

    # dosfstools for ESP
    chroot_exec "
        if [[ -f /sources/dosfstools-*.tar.gz ]]; then
            cd /sources && tar xf dosfstools-*.tar.gz && cd dosfstools-*/ && \
            ./configure --prefix=/usr --enable-compat-symlinks --mandir=/usr/share/man && \
            make && make install && \
            cd /sources && rm -rf dosfstools-*/
        fi
    " || true
}

# --- Finalization ---

system_finalize() {
    einfo "Finalizing system..."

    # Create /etc/os-release
    chroot_exec "
        cat > /etc/os-release << 'OSEOF'
NAME=\"Linux From Scratch\"
VERSION=\"${LFS_VERSION}\"
ID=lfs
PRETTY_NAME=\"Linux From Scratch ${LFS_VERSION}\"
VERSION_CODENAME=\"\"
HOME_URL=\"https://www.linuxfromscratch.org/\"
OSEOF
    "

    # Create /etc/lfs-release
    chroot_exec "echo ${LFS_VERSION} > /etc/lfs-release"

    # Create /etc/lsb-release
    chroot_exec "
        cat > /etc/lsb-release << 'LSBEOF'
DISTRIB_ID=\"Linux From Scratch\"
DISTRIB_RELEASE=\"${LFS_VERSION}\"
DISTRIB_CODENAME=\"\"
DISTRIB_DESCRIPTION=\"Linux From Scratch\"
LSBEOF
    "

    # Create /etc/inputrc
    chroot_exec "
        cat > /etc/inputrc << 'INPUTEOF'
set horizontal-scroll-mode Off
set meta-flag On
set input-meta On
set convert-meta Off
set output-meta On
set bell-style none

\"\\eOd\": backward-word
\"\\eOc\": forward-word
\"\\e[1~\": beginning-of-line
\"\\e[4~\": end-of-line
\"\\e[5~\": beginning-of-history
\"\\e[6~\": end-of-history
\"\\e[3~\": delete-char
\"\\e[2~\": quoted-insert
\"\\eOH\": beginning-of-line
\"\\eOF\": end-of-line
\"\\e[H\": beginning-of-line
\"\\e[F\": end-of-line
INPUTEOF
    "

    # Create /etc/shells
    chroot_exec "
        cat > /etc/shells << 'SHELLEOF'
/bin/sh
/bin/bash
SHELLEOF
    "

    # Create /etc/profile
    chroot_exec "
        cat > /etc/profile << 'PROFEOF'
export LANG=\$(cat /etc/locale.conf 2>/dev/null | grep LANG= | cut -d= -f2)
export PATH=/usr/bin:/usr/sbin
export HISTSIZE=1000
export HISTFILESIZE=2000

for script in /etc/profile.d/*.sh; do
    [ -r \"\$script\" ] && . \"\$script\"
done
unset script

umask 022
PROFEOF
    "

    # Clean up
    chroot_exec "
        rm -rf /tmp/*
        find /usr/lib /usr/libexec -name '*.la' -delete 2>/dev/null || true
        find /usr -depth -name '$(uname -m)-lfs-linux-gnu*' -delete 2>/dev/null || true
    "

    einfo "System finalization complete"
}

# --- Extra packages ---

install_extra_packages() {
    if [[ -z "${EXTRA_PACKAGES:-}" ]]; then
        einfo "No extra packages to install"
        return 0
    fi

    ewarn "Extra packages require manual compilation from BLFS"
    ewarn "Packages requested: ${EXTRA_PACKAGES}"
    einfo "These should be built after first boot"
}
